#ifndef GENO_CONFIG_H
#define GENO_CONFIG_H

#include <QtCore/qglobal.h>

#define GENO_VERSION_MAJOR 1
#define GENO_VERSION_MINOR 0
#define GENO_VERSION_PATCH 0
#define GENO_VERSION_STR   "1.0.0"
#define GENO_VERSION       GENO_VERSION_CHECK(GENO_VERSION_MAJOR, GENO_VERSION_MINOR, GENO_VERSION_PATCH)
#define GENO_VERSION_CHECK QT_VERSION_CHECK

#endif // GENO_CONFIG_H
